- name: Install required base packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - git
    - python-mysqldb
    - zip
    - unzip

- name: Add .bash_profile
  template:
    src=.bash_profile.j2
    dest=/home/{{ www_user }}/.bash_profile
